import Divider from "@/components/Divider";
import Footer from "@/components/Footer";
import { Navbar, NavbarItem } from "@/components/Navbar";
import ParallaxImage from "@/components/ParallaxImage";
import Section, { SectionContent } from "@/components/Section";
import Head from "next/head";
import { type PropsWithChildren } from "react";

function Text({
  children,
  className = "",
}: { className?: string } & PropsWithChildren) {
  return (
    <div className={`mb-12 w-full text-3xl leading-10 ${className}`}>
      {children}
    </div>
  );
}

function ArticleImage({ imageUrl }: { imageUrl: string }) {
  return <ParallaxImage src={imageUrl} className="mb-20 aspect-video w-full" />;
}
// function ArticleImage({ imageUrl }: { imageUrl: string }) {
//   return (
//     <div className="relative mb-20 aspect-video w-full overflow-hidden rounded-xl bg-gray-500">
//       <Image
//         layout="fill"
//         src={imageUrl}
//         alt="Image not found"
//         className="h-full w-full object-cover object-center"
//       />
//     </div>
//   );
// }

export default function About() {
  return (
    <>
      <Head>
        <title>Fleet | About</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar>
        <NavbarItem to="/" name="Home" />
        <NavbarItem to="/services" name="Services" />
        <NavbarItem to="/about" name="About" />
      </Navbar>
      <main className="h-full min-h-screen w-full ">
        <div className="flex h-full min-h-screen flex-col items-center justify-center">
          <div className="aspect-video w-1/3 min-w-[200px] overflow-hidden rounded-xl">
            <video
              src="/our-story.mp4"
              className="w-full object-cover"
              autoPlay
              muted
              loop
              playsInline
            />
          </div>
          <h1 className="mb-0 mt-5 text-center text-8xl tracking-tight">
            Our Story. Our Perspective.
          </h1>
          <h2 className="text-3xl font-thin tracking-tight">
            the story of how our founders conclude that current logistics
            solution sucks.
          </h2>
          <Divider />
        </div>
        <Section>
          <SectionContent>
            <ArticleImage imageUrl="/images/traditional.jpg" />
            <Text>
              Our story begins with a simple realization:{" "}
              <span className="font-bold">
                traditional logistics solutions are often sluggish, rigid, and
                fail to adapt to the ever-changing demands of today&apos;s
                fast-paced world.{" "}
              </span>{" "}
              As a team of passionate innovators, we grew tired of the
              limitations imposed by the status quo and set out on a mission to
              revolutionize the way goods are transported and stored.
            </Text>
            <Text>
              Drawing inspiration from the power of decentralization, we
              envisioned a logistics ecosystem where individuals and businesses
              could seamlessly participate as &quot;ghost warehouses and sorting
              centers.&quot; We wanted to harness the untapped potential of idle
              spaces, spare capacity, and underutilized resources to create
              an&nbsp;
              <span className="font-bold">
                agile and efficient network that could keep pace with the
                dynamic needs of modern commerce.
              </span>
            </Text>
            <Text className="italic">Thus, Fleet was born.</Text>
            <Divider />

            <ArticleImage imageUrl="/images/warehouse.jpg" />
            <Text>
              At Fleet, we believe that the future of logistics lies in
              empowering individuals and businesses to become an integral part
              of the supply chain. By leveraging our innovative platform,{" "}
              <span className="font-bold">
                anyone with available space can transform their idle assets into
                valuable logistics hubs.
              </span>{" "}
              These &quot;ghost warehouses and sorting centers&quot; can
              seamlessly integrate into our network,&nbsp;
              <span className="italic">
                contributing to the seamless movement of goods while earning
                income from their underutilized resources.
              </span>
            </Text>
            <Text>
              But Fleet is more than just a platform -{" "}
              <span className="font-bold">it&apos;s a community.</span> We
              foster a collaborative environment where our members can connect,
              share insights, and work together to optimize the efficiency of
              our logistics network. Through a blend of cutting-edge technology,
              real-time data analysis, and smart algorithms, we ensure that
              every movement within the&nbsp;
              <span className="font-bold italic">
                Fleet ecosystem is streamlined, cost-effective, and sustainable.
              </span>
            </Text>
            <Divider />

            <ArticleImage imageUrl="/images/sustainability.jpg" />
            <Text>
              Our commitment to excellence extends beyond efficiency.{" "}
              <span className="font-bold">
                We place a strong emphasis on sustainability, striving to reduce
                the carbon footprint of logistics operations.
              </span>{" "}
              By optimizing routes, consolidating shipments, and utilizing
              shared resources, we minimize waste and promote environmentally
              friendly practices. At Fleet, we believe that responsible
              logistics is an essential pillar of a better future for both
              businesses and our planet.
            </Text>
            <Text>
              Join us on this exciting journey as we reshape the world of
              logistics and transportation. Whether you&apos;re a business
              looking for efficient and cost-effective solutions or an
              individual seeking to contribute your space and resources, Fleet
              welcomes you with open arms.
            </Text>

            <Text>
              Together, let&apos;s unlock the true potential of decentralized
              logistics, embrace the power of collaboration, and pave the way
              for a faster, greener, and more inclusive future. Welcome to
              Fleet, where logistics meets innovation!
            </Text>
          </SectionContent>
        </Section>
      </main>
      <Footer />
    </>
  );
}
