import Divider from "@/components/Divider";
import Footer from "@/components/Footer";
import { Navbar, NavbarItem } from "@/components/Navbar";
import ParallaxImage from "@/components/ParallaxImage";
import Section, { SectionContent } from "@/components/Section";
import Head from "next/head";
import { type PropsWithChildren } from "react";

function Text({ children }: PropsWithChildren) {
  return <div className="mb-12 w-full text-3xl leading-10">{children}</div>;
}

function ArticleImage({ imageUrl }: { imageUrl: string }) {
  return <ParallaxImage src={imageUrl} className="mb-20 aspect-video w-full" />;
}
// function ArticleImage({ imageUrl }: { imageUrl: string }) {
//   return (
//     <div className="relative mb-20 aspect-video w-full overflow-hidden rounded-xl bg-gray-500">
//       <Image
//         layout="fill"
//         src={imageUrl}
//         alt="Image not found"
//         className="h-full w-full object-cover object-center"
//       />
//     </div>
//   );
// }

export default function About() {
  return (
    <>
      <Head>
        <title>Fleet | About</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar>
        <NavbarItem to="/" name="Home" />
        <NavbarItem to="/services" name="Services" />
        <NavbarItem to="/about" name="About" />
      </Navbar>
      <main className="h-full min-h-screen w-full ">
        <div className="flex h-full min-h-screen flex-col items-center justify-center">
          <div className="aspect-video w-1/3 min-w-[200px] overflow-hidden rounded-xl">
            <video
              src="/our-story.mp4"
              className="w-full object-cover"
              autoPlay
              muted
              loop
              playsInline
            />
          </div>
          <h1 className="mb-0 mt-5 text-center text-8xl tracking-tight">
            Our Story. Our Perspective.
          </h1>
          <h2 className="text-3xl font-thin tracking-tight">
            The story of how everyone here concludes that current logistics
            solution sucks.
          </h2>
          <Divider />
        </div>
        <Section>
          <SectionContent>
            <ArticleImage imageUrl="/images/logistics.jpg" />
            <Text>
              Once upon a time, our team of passionate individuals came together
              with a common frustration:{" "}
              <span className="font-bold">
                the archaic and cumbersome nature of traditional logistics
                management solutions.
              </span>{" "}
              We were tired of witnessing the inefficiencies, the lack of
              transparency, and the countless hours wasted on manual processes.{" "}
              <span className="font-bold underline">
                We knew there had to be a better way.
              </span>
            </Text>
            <Text>
              As we delved deeper into the world of logistics, we discovered
              that businesses of all sizes were grappling with similar
              challenges. The existing software solutions were often{" "}
              <span className="font-bold">
                expensive, complex, and inflexible,
              </span>{" "}
              making it difficult for small and medium-sized enterprises to
              streamline their operations effectively. This realization ignited
              our desire to create a revolutionary platform that would transform
              the way logistics is managed.
            </Text>
            <Divider />

            <ArticleImage imageUrl="/images/idea.jpg" />
            <Text>
              That&apos;s how Fleet was born - an open-sourced web-app based
              logistics management solution. Our primary goal was to empower
              businesses with a user-friendly, cost-effective, and scalable tool
              that would optimize their logistics operations.{" "}
              <span className="font-bold">
                We envisioned a platform that would be accessible to all,
                regardless of the size of their fleet or budget.
              </span>
            </Text>
            <Text>
              Through our open-source approach, we aimed to foster a
              collaborative community where logistics professionals, developers,
              and businesses could contribute, innovate, and customize the
              software to meet their specific needs. We believed that by
              harnessing the collective wisdom and expertise of the community,
              we could create{" "}
              <span className="font-bold">
                a comprehensive and adaptable solution that would benefit
                everyone involved in the logistics ecosystem.
              </span>
            </Text>
            <Text>
              With &quot;Fleet,&quot; we set out to tackle the pain points we
              had witnessed firsthand. We designed intuitive dashboards that
              provided real-time visibility into the entire logistics process -
              from order management and dispatching to tracking and delivery.
              Automation became the cornerstone of our solution, enabling
              businesses to automate repetitive tasks, reduce errors, and save
              valuable time.
            </Text>
            <Text>
              Transparency and communication were paramount to us. We
              incorporated features that allowed seamless collaboration between
              drivers, dispatchers, and customers, ensuring everyone was on the
              same page throughout the journey. Advanced analytics and reporting
              capabilities provided valuable insights into performance metrics,
              helping businesses make data-driven decisions to optimize their
              operations further.
            </Text>
            <Divider />

            <Text>
              <span className="font-bold">
                But what truly set us apart was our commitment to being
                open-sourced.
              </span>{" "}
              We believed that the collective intelligence of the community
              could drive continuous innovation, allowing &quot;Fleet&quot; to
              evolve and adapt to the ever-changing demands of the logistics
              industry. By sharing our source code, we fostered an environment
              of collaboration, where developers could contribute their
              expertise, suggest improvements, and build upon the foundation we
              had laid.
            </Text>
            <Text>
              We knew that the journey ahead wouldn&apos;t be easy. However,
              armed with a deep passion for revolutionizing the logistics
              industry and a steadfast belief in the power of collaboration, we
              embarked on this ambitious endeavor. With &quot;Fleet,&quot; we
              aimed to empower businesses, simplify logistics management, and
              contribute to a more efficient and sustainable future.
            </Text>
            <Text>
              And so, our story continues as we work hand in hand with our
              community, striving to shape the future of logistics through
              innovation, openness, and a relentless pursuit of excellence.
            </Text>
          </SectionContent>
        </Section>
      </main>
      <Footer />
    </>
  );
}
